
version: "3.9"
services:
  openhome-api:
    build: ./api
    container_name: openhome-api
    restart: unless-stopped
    volumes:
      - saves:/data/saves
    ports:
      - "8095:8095"

  openhome-web:
    build: ./web
    container_name: openhome-web
    restart: unless-stopped
    ports:
      - "8085:80"
    depends_on:
      - openhome-api

volumes:
  saves:
